# Solution Author: Arunabha Sarkar, https://github.com/NV2017

# 002 Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

## https://projecteuler.net/problem=2

a = 1
b = 2
sum = 2
while (b < 4000000)
{
  c = a
  a = b
  b = c + b
  if (b%%2==0)
  {
    sum = sum + b
  }
}
print(sum)